upstream_url: https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/awesome_agent_skills/fullstack-developer
last_synced: 2026-02-26
notes: "翻译了 frontmatter 中的 description 并补充了 short-description。其余指南保持英文原版。"
