<#
.SYNOPSIS
    将 skills-engine 链接到目标项目

.DESCRIPTION
    为指定平台在目标项目中创建链接/文件，使 AI Agent 能自动发现 skills-engine 的内容。
    目录链接使用 Junction（无需管理员权限）；文件链接使用 SymbolicLink（需开发者模式或管理员）。

.PARAMETER TargetProject
    目标项目的路径（绝对路径）

.PARAMETER Platforms
    要链接的平台，可选：gemini, claude, codex, trae。默认全部。

.EXAMPLE
    .\setup.ps1 C:\path\to\my-project
    .\setup.ps1 C:\path\to\my-project -Platforms gemini,claude
    .\setup.ps1 C:\path\to\my-project -Platforms codex,trae
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$TargetProject,

    [string[]]$Platforms = @("gemini", "claude", "codex", "trae")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$EngineRoot = $PSScriptRoot
$Target = $TargetProject

# ── 验证目标目录 ──────────────────────────────────────────────
if (-not (Test-Path $Target -PathType Container)) {
    Write-Error "Target directory not found: $Target"
    exit 1
}
$Target = (Resolve-Path $Target).Path

Write-Host ""
Write-Host "skills-engine: $EngineRoot" -ForegroundColor DarkGray
Write-Host "target:        $Target" -ForegroundColor DarkGray
Write-Host ""

# ── 辅助函数 ──────────────────────────────────────────────────

function New-Junction {
    param([string]$LinkPath, [string]$TargetPath)
    if (Test-Path $LinkPath) {
        Write-Host "  [跳过] 已存在：$LinkPath" -ForegroundColor Yellow
        return
    }
    New-Item -ItemType Junction -Path $LinkPath -Target $TargetPath | Out-Null
    Write-Host "  [Junction] $LinkPath → $TargetPath" -ForegroundColor Green
}

function New-FileSymlink {
    param([string]$LinkPath, [string]$TargetPath)
    if (Test-Path $LinkPath) {
        Write-Host "  [跳过] 已存在：$LinkPath" -ForegroundColor Yellow
        return
    }
    try {
        New-Item -ItemType SymbolicLink -Path $LinkPath -Target $TargetPath | Out-Null
        Write-Host "  [Symlink] $LinkPath → $TargetPath" -ForegroundColor Green
    }
    catch {
        # 如果没有权限，回退为复制文件（并注明）
        Copy-Item -Path $TargetPath -Destination $LinkPath
        Write-Host "  [copy-no symlink perm] $LinkPath <- $TargetPath" -ForegroundColor Magenta
        Write-Host "    Tip: enable Developer Mode for real symlinks" -ForegroundColor DarkYellow
    }
}

function Ensure-Dir {
    param([string]$Path)
    if (-not (Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path | Out-Null
    }
}

# ── 各平台链接逻辑 ────────────────────────────────────────────

foreach ($platform in $Platforms) {
    switch ($platform.ToLower()) {

        "gemini" {
            Write-Host "[Gemini]" -ForegroundColor Cyan
            $geminiDir = Join-Path $Target ".gemini"
            Ensure-Dir $geminiDir
            $skillsLink = Join-Path $geminiDir "skills"
            $skillsSrc  = Join-Path $EngineRoot "skills"
            New-Junction -LinkPath $skillsLink -TargetPath $skillsSrc

            $geminiMdLink = Join-Path $Target "GEMINI.md"
            $geminiMdSrc = Join-Path $EngineRoot "adapters\GEMINI.md"
            New-FileSymlink -LinkPath $geminiMdLink -TargetPath $geminiMdSrc
        }

        "claude" {
            Write-Host "[Claude Code]" -ForegroundColor Cyan
            $claudeLink = Join-Path $Target "CLAUDE.md"
            $claudeSrc = Join-Path $EngineRoot "adapters\CLAUDE.md"
            New-FileSymlink -LinkPath $claudeLink -TargetPath $claudeSrc
        }

        "codex" {
            Write-Host "[Codex CLI]" -ForegroundColor Cyan
            $agentsLink = Join-Path $Target "AGENTS.md"
            $agentsSrc = Join-Path $EngineRoot "adapters\AGENTS.md"
            New-FileSymlink -LinkPath $agentsLink -TargetPath $agentsSrc
        }

        "trae" {
            Write-Host "[Trae]" -ForegroundColor Cyan
            # Trae 使用 AGENTS.md（项目根，与 codex 共享）
            $agentsLink = Join-Path $Target "AGENTS.md"
            $agentsSrc = Join-Path $EngineRoot "adapters\AGENTS.md"
            New-FileSymlink -LinkPath $agentsLink -TargetPath $agentsSrc

            # Trae 专属：.trae/rules/project_rules.md
            $traeRulesDir = Join-Path $Target ".trae\rules"
            Ensure-Dir $traeRulesDir
            $traeRulesFile = Join-Path $traeRulesDir "project_rules.md"
            if (-not (Test-Path $traeRulesFile)) {
                $lines = @(
                    "# Project Rules",
                    "",
                    "<!-- Generated by skills-engine/setup.ps1 -->",
                    "<!-- RULES: $EngineRoot\core\RULES.md -->",
                    "<!-- CONVENTIONS: $EngineRoot\core\CONVENTIONS.md -->"
                )
                $lines -join "`r`n" | Set-Content -Path $traeRulesFile -Encoding UTF8
                Write-Host "  [created] $traeRulesFile" -ForegroundColor Green
            } else {
                Write-Host "  [skip] exists: $traeRulesFile" -ForegroundColor Yellow
            }
        }

        default {
            Write-Host "[warn] unknown platform: $platform (options: gemini, claude, codex, trae)" -ForegroundColor Red
        }
    }
}

Write-Host ""
Write-Host "Done!" -ForegroundColor Green
Write-Host "Tip: if files were [copy] instead of [Symlink], re-run this script after updating skills-engine." -ForegroundColor DarkGray
Write-Host ""
