upstream_url: https://github.com/vercel-labs/agent-skills/tree/main/skills/react-best-practices
last_synced: 2026-02-26
notes: "重命名文件夹为 vercel-react-best-practices，翻译了 frontmatter 中的 description 并补充了 short-description，底层内容保持原版英文。"
