name: Docker CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Check image size
        run: |
          SIZE=$(docker image inspect ${{ github.repository }}:latest --format='{{.Size}}' 2>/dev/null || echo "0")
          if [ "$SIZE" != "0" ]; then
            SIZE_MB=$((SIZE / 1024 / 1024))
            echo "📊 Image size: ${SIZE_MB}MB"
          fi
